[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  # Ruta al archivo que la función necesita incluir
  included_files = ["public/data/courses.json"]