[build]
  # Directorio donde están los archivos públicos del frontend.
  publish = "public"
  # Directorio donde Netlify encontrará las funciones del servidor.
  functions = "netlify/functions"

[[redirects]]
  # Redirige todas las llamadas a '/api/*' a nuestra función del servidor.
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200